lobby_time: 10
min_player: 3
max_player: 12
cycle_time:
  day: 420
  night: 60
role_info:
  citizen:
    max: 3
    name: Dorpeling
  mayor:
    max: 1
    name: Burgemeester
  protector:
    max: 1
    uses: 1
    name: Beschermengel
  temptress:
    max: 1
    name: Verleidster
  hero:
    max: 1
    uses: 3
    name: Held
  watcher:
    max: 1
    name: Wachter
  alpha:
    name: Alpha Wolf
  beta:
    name: Beta Wolf
  omega:
    name: Omega Wolf
  murderer:
    name: Moordenaar
  madman:
    max: 2
    name: Dorpsgek
lobby_location:
teams:
  blue:
    rgb: "53:57:157"
  yellow:
    rgb: "248:198:39"
  pink:
    rgb: "237:141:172"
  brown:
    rgb: "114:71:40"
  black:
    rgb: "20:21:25"
  gray:
    rgb: "142:142:134"
  orange:
    rgb: "240:118:19"
  purple:
    rgb: "121:42:172"
  aqua:
    rgb: "58:175:217"
  green:
    rgb: "112:185:25"
  white:
    rgb: "233:236:236"
  red:
    rgb: "161:39:34"
names:
  - 'George'
  - 'David'
  - 'Max'
  - 'Sam'
  - 'Mike'
  - 'John'
  - 'James'
  - 'Matthew'
  - 'Paul'
  - 'Mark'
  - 'Daniel'
  - 'Nathan'
  - 'Thomas'
  - 'Jason'
  - 'Steven'
  - 'William'
  - 'Scott'
  - 'Frank'
  - 'Brian'
  - 'Kevin'
  - 'Richard'
  - 'Dennis'
  - 'Gary'
  - 'Keith'
  - 'Wayne'
  - 'Austin'
  - 'Ethan'
  - 'Evan'
  - 'Dylan'
  - 'Linda'
  - 'Sarah'
  - 'Karen'
  - 'Betty'
  - 'Susan'
  - 'Ashley'
  - 'Laura'
  - 'Helen'
  - 'Emma'
  - 'Heather'
  - 'Martha'
  - 'Megan'
  - 'Hannah'
  - 'Alice'
  - 'Olivia'
  - 'Tiffany'
  - 'Rose'
  - 'Theresa'
  - 'Ann'
  - 'Andrea'
  - 'Judith'