main: org.pixelgalaxy.WerewolfMain
name: Werewolves
version: 0.1
author: HungryDev
api-version: 1.13
commands:
  game:
    description: "Game related commands for admins only"
    permission: "game.edit"
  skipday:
    description: "for skipping day as gamemaster"